INSERT INTO dbo.Shipments (Origin, Destination, Distance, Status, TruckId)
VALUES
    ('Toronto', 'Montreal', 100, 'In Transit', 28),
    ('Calgary', 'Vancouver', 110, 'Delivered', 29),
    ('Ottawa', 'Quebec City', 120, 'Pending', 30),
    ('Halifax', 'St. John''s', 130, 'Cancelled', 31), 
    ('Edmonton', 'Saskatoon', 140, 'In Transit', 32),
    ('Regina', 'Winnipeg', 150, 'Delivered', 33),
    ('London', 'Hamilton', 160, 'Pending', 34),
    ('Brampton', 'Mississauga', 170, 'Cancelled', 35),
    ('Niagara Falls', 'Toronto', 180, 'In Transit', 36),
    ('Guelph', 'Kitchener', 190, 'Delivered', 37),
    ('Windsor', 'Sudbury', 200, 'Pending', 38),
    ('Thunder Bay', 'North Bay', 210, 'Cancelled', 39),
    ('Barrie', 'Peterborough', 220, 'In Transit', 40),
    ('Cornwall', 'Kingston', 230, 'Delivered', 41),
    ('Markham', 'Richmond Hill', 240, 'Pending', 42),
    ('Pickering', 'Oshawa', 250, 'Cancelled', 43),
    ('Stratford', 'Chatham', 260, 'In Transit', 44),
    ('Timmins', 'Orillia', 270, 'Delivered', 45),
    ('Sarnia', 'Niagara Falls', 280, 'Pending', 46),
    ('Burlington', 'Toronto', 290, 'Cancelled', 47),
    ('Mississauga', 'London', 300, 'In Transit', 48),
    ('Toronto', 'Ottawa', 310, 'Delivered', 49),
    ('Windsor', 'Hamilton', 320, 'Pending', 50),
    ('Edmonton', 'Calgary', 330, 'Cancelled', 51);